### ISSUE TITLE
컴포넌트 시작 시 오류

### ISSUE THREAD

**Issue by digitie** [oukene/smartthings_customize#28]
좋은 컴포넌트 제작해주셔서 감사드립니다.

현재 Edge 드라이버로 Tuya 전동커튼이 연동되어 있는데요.
그 때문인지 컴포넌트 시작 시 아래와 같은 에러가 발생합니다.

ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 집 for smartthings_customize
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_customize/__init__.py", line 214, in async_setup_entry
    broker = await hass.async_add_import_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_customize/__init__.py", line 387, in __init__
    self._assignments = self._assign_capabilities(devices)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_customize/__init__.py", line 417, in _assign_capabilities
    assigned = platform_module.get_capabilities(capabilities)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_customize/cover.py", line 68, in get_capabilities
    Capability.window_shade_level,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Capability' has no attribute 'window_shade_level'

**Comment by oukene** [comment]
위의 에러가 조금 이해가 안갑니다. 저도 cover 기기가 등록되어있는게 있는데 에러가 안나거든요
에러 내용만 보자면 Capability 정의된 목록중에 window_shade_level 이 없다는건데, 이 목록이 ha 에 내장된 pysmartthings 라는 모듈에서 정의되어있는 목록이라서 이 에러를 어떻게 받아들여야 할지 모르겠습니다.
